#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: in Si(lico)
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6497b1
  secondary: 50788d  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jessie Ebie
  pic: 1
  position: Graduate Student</br>Arizona State University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jessicaebie
    - title: link
      url: http://www.tedpavlic.com/
      
- name: Ted Pavlic
  pic: 2
  position: Assistant Professor</br>Arizona State University
  social:
    - title: twitter
      url: https://twitter.com/TedPavlic
    - title: google-plus
      url: https://plus.google.com/u/0/+TedPavlic
    - title: linkedin
      url: https://www.linkedin.com/in/tedpavlic
    - title: link
      url: http://www.tedpavlic.com/

- name: Simon Garnier
  pic: 3
  position: Assistant Professor</br>New Jersey Institute of Technology
  social:
    - title: twitter
      url: https://twitter.com/sjmgarnier
    - title: google-plus
      url: https://plus.google.com/u/0/+SimonGarnier
    - title: linkedin
      url: https://www.linkedin.com/in/simongarnier/
    - title: link
      url: http://www.theswarmlab.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Languages
languages: [NetLogo, R, Python]

# Disciples
disciplines: [Biology, Physics, Mathematics]





